EEEP-1423: Implemented stub for Sessions service
apriorit/Soroka-Sessions pull request #1
Opened 2019-09-12 15:52 UTC by ProximaCentauri1989

2019-09-19 06:11 UTC, belyshevdenis requested changes

2019-09-19 06:11 UTC, belyshevdenis commented on cmd/sessionssvc/utils.go
> +	c "github.com/hashicorp/consul/api"
The original package name is short, so alias is not needed. Same case in another files

2019-09-19 06:11 UTC, belyshevdenis commented on composition/service/serv.crt
> +-----BEGIN CERTIFICATE-----
Please remove keys from repo and leave instruction about how generate them

2019-09-19 06:11 UTC, belyshevdenis commented on cmd/sessionssvc/main.go
> +		secret     = flag.String("consul.service.secret", "service/secret", "Secret to sign JWT")
Maybe you should name it more specifically - signing secret or signing key, because service secret looks like a secret needed to access the service, not the secret that is used by service

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/config/config.go
> +type LoggerSingleton struct {
You can make a logger interface global (if you want to) without wrapping it to the struct LoggerSIngleton

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/config/config.go
> +var pkey *publicKey
Is there a real need to make it global? Please track the usage of this object and make a struct member from it if there is such possibility.

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/constants/constants.go
> +	ClientUnkown          string = "Client are unknown"
is unknown

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/handlers/handlers.go
> +	conf.GetLogger().Logger.Log("refresh_token", e.RefreshToken.Token)
Actually the refresh token is a sort of a client secret, so you should not to log such things

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/handlers/handlers.go
> +	conf.GetLogger().Logger.Log("a", reqCurrentService.AccessToken, "r", reqCurrentService.RefreshToken)
You should not log such things

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/handlers/utils.go
> +func GetCookieWithExpiredToken(rt *m.TokenData, loc *time.Location) http.Cookie {
rt is not used, moreover it is passed as nil from function AddCookie

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/handlers/utils.go
> +	expire := time.Unix(time.Date(1976, 1, 1, 0, 0, 0, 0, loc).Unix(), 0).In(loc)
Expired timestamp is just zero (timestamp 0) - you should not create it from actual date when timestamp is born.

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/handlers/utils_test.go
> +func TestMultiError(t *testing.T) {
There is no need to create a test for external functionality. Also, I do not see where multierror is used - probably you should remove this dependency

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/handlers/utils_test.go
> +func TestFormUnixData(t *testing.T) {
1. I've already mentioned that invalid timestamp is just a zero
2. This function tests the obvious thing and not used project code, so it should be removed.

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/models/service.go
> +	_ "github.com/hashicorp/go-multierror"
not used

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/service/middlewares.go
> +		lmw.logger.Log("method", "Login", "usename", ld.UserName, "password", ld.Password, "took", time.Since(begin), "err", err)
You have logged a password. This is a serious breach in security

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/service/middlewares.go
> +		lmw.logger.Log("method", "CheckToken", "token", ctd.AccessToken, "took", time.Since(begin), "err", err)
Do not log the tokens

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/service/service_test.go
> +func TestGetRawAccessToken(t *testing.T) {
Remove empty test
Here you can check at least the output of service methods

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/service/utils.go
> +	sStub.Logger.Log("method", "EnsureUserCreds", "username", username, "password", password)
Do not log passwords

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/service/utils.go
> +//GetUserProfile query user profile by email from Users database
There is no access to the database, there is a call to another service instead

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/service/utils.go
> +	sStub.Logger.Log("Method", "GenerateToken", "Sign secret", sStub.secret)
Do not log the secret

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/service/utils.go
> +func CreatePayload(tokenType, cid, iss string, mask int64) (jwt.MapClaims, int64) {
It is better to make enum from tokenType

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/service/utils.go
> +	sStub.Logger.Log("method", "CheckTokenValidness", "begin", "begin")
What is "begin" and "begin3" (in the next log)?

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/service/utils.go
> +	return claims.Valid() != nil
Valid() can check not only the expiration date. You'd better to research what Valid() method does and rename current function or check only expiration date directly in current function.

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/service/utils_test.go
> +func TestCheckTokenValidness_ValidTokenValidClaim(t *testing.T) {
Please add the test for CheckTokenValidness when the function ensures that token is NOT valid.

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/service/service.go
> +	//3. Restore session sensetive data from session database
Please create an interface for the refresh token database and the stub behind it. Use this interface to save|load|delete tokens. When this service become real, all you need to do is to implement real database instead of stub, so you should not read all the code in future to understand what you have to do.

2019-09-19 06:11 UTC, belyshevdenis commented on pkgs/service/service.go
> +	return &SessionsServiceStub{
As I see, the implementation of this struct is pretty real except the usage of real database, so please do not call it a stub. Use interfaces inside it to call not implemented functionality (see comments below).

2019-09-19 11:44 UTC, ProximaCentauri1989 commented on pkgs/service/utils.go
> +	sStub.Logger.Log("method", "CheckTokenValidness", "begin", "begin")
I used them for analyzing a strange bug in token parsing process and forget to delete them.

2019-09-19 11:59 UTC, ProximaCentauri1989 commented on pkgs/config/config.go
> +var pkey *publicKey
It needed on the handler level (where decoding of raw request occur) for creating an HTTP client with the public key which is used for request for token verification. It a topmost level on which I don't have access to service structure. That why it's global.

2019-09-20 13:28 UTC, belyshevdenis requested changes

2019-09-20 13:28 UTC, belyshevdenis commented on pkgs/db/db.go
> +		//Real database
Return nil and error "not implemented"

2019-09-20 13:28 UTC, belyshevdenis commented on pkgs/db/db.go
> +		db  SessionsDbStub
init this in if {} scope

2019-09-20 13:28 UTC, belyshevdenis commented on pkgs/db/stub.go
> +		return "", errors.ErrClientUnkown
UnkNown

2019-09-20 13:28 UTC, belyshevdenis commented on pkgs/db/stub.go
> +	db.Mtx.Lock()
Use RLock and RUnlock on Get operation

2019-09-20 13:28 UTC, belyshevdenis commented on pkgs/service/utils.go
> +		claims = jwt.MapClaims{
You can use jwt.StandardClaims instead

2019-09-20 13:37 UTC, ProximaCentauri1989 commented on pkgs/config/config.go
> +type LoggerSingleton struct {
This, in fact, is global config, like in Users. I just changed the name from LoggerConfig to  LoggerSingleton to in order to emphasize its nature.

2019-09-20 13:38 UTC, ProximaCentauri1989 commented on pkgs/constants/constants.go
> +	ClientUnkown          string = "Client are unknown"
Changed

2019-09-20 13:48 UTC, ProximaCentauri1989 commented on pkgs/db/stub.go
> +	db.Mtx.Lock()
I think in Exist it's also necessary to use read Lock and read Unlock. Should I change it too?

2019-09-20 14:01 UTC, ProximaCentauri1989 commented on pkgs/service/utils.go
> +		claims = jwt.MapClaims{
How important is this? If I change it to StandardClaims I must implement an additional structure for holding StandardClaims and non-standard mask claim.

2019-09-20 14:02 UTC, ProximaCentauri1989 commented on pkgs/db/db.go
> +		//Real database
Changed

2019-09-20 14:02 UTC, ProximaCentauri1989 commented on pkgs/db/db.go
> +		db  SessionsDbStub
Changed

2019-09-20 14:02 UTC, ProximaCentauri1989 commented on pkgs/db/stub.go
> +		return "", errors.ErrClientUnkown
Changed

2019-09-20 15:08 UTC, belyshevdenis commented on pkgs/service/utils.go
> +		claims = jwt.MapClaims{
This is not important, it is just a hint. closing

2019-09-20 15:10 UTC, belyshevdenis commented on pkgs/db/stub.go
> +	db.Mtx.Lock()
It is called by reader, so generally you should use reader lock.

2019-09-20 15:20 UTC, ProximaCentauri1989 commented on pkgs/db/stub.go
> +	db.Mtx.Lock()
Changed

2019-09-20 15:22 UTC, merged